sudo: false
language: python
dist: trusty

matrix:
  include:
    # Default Python
    - env: TOXENV=flake8
    - env: TOXENV=markdown-lint
      before_install: gem install mdl
    - env: TOXENV=linkchecker
    - env: TOXENV=jshint
      before_install: npm install -g jshint
    - env: TOXENV=csslint
      before_install: npm install -g csslint
    # Python version specific
    - python: '2.6'
      env: TOXENV=py26-integration
    - python: '2.6'
      env: TOXENV=py26-min-req
    - python: '2.6'
      env: TOXENV=py26-unittests
    - python: '2.7'
      env: TOXENV=py27-integration
    - python: '2.7'
      env: TOXENV=py27-min-req
    - python: '2.7'
      env: TOXENV=py27-unittests
    - python: '3.3'
      env: TOXENV=py33-integration
    - python: '3.3'
      env: TOXENV=py33-min-req
    - python: '3.3'
      env: TOXENV=py33-unittests
    - python: '3.4'
      env: TOXENV=py34-integration
    - python: '3.4'
      env: TOXENV=py34-min-req
    - python: '3.4'
      env: TOXENV=py34-unittests
    - python: '3.5'
      env: TOXENV=py35-integration
    - python: '3.5'
      env: TOXENV=py35-min-req
    - python: '3.5'
      env: TOXENV=py35-unittests
    - python: 'pypy'
      env: TOXENV=pypy-integration
    - python: 'pypy'
      env: TOXENV=pypy-min-req
    - python: 'pypy'
      env: TOXENV=pypy-unittests
    - python: 'pypy3'
      env: TOXENV=pypy3-integration
    - python: 'pypy3'
      env: TOXENV=pypy3-min-req
    - python: 'pypy3'
      env: TOXENV=pypy3-unittests

install:
  - pip install codecov
  - pip install tox

script:
  - git clean -f -d -x
  - tox

after_success: codecov

deploy:
  provider: pypi
  user: mkdocsdeploy
  distributions: "sdist bdist_wheel"
  password:
    secure: b4f6y1xw5B/RXXnOu6JIaNcgOBZ0/CkNaMeEXsoQSewYZNwobLPYALY9WaaOblarwrVa5NRD3e4x6SoL1/1NzQxfhCNMn7L82sssmtevnK+mSuUp4IZQa8WKyz+xLfnk28TlHgQbctAU9NaeQ6GuEflTRD7Bp8+xJ1C7h+yBUnw=
  on:
    tags: true
    repo: mkdocs/mkdocs
    condition: "$TOXENV = py27-integration"
